# standard library imports

# local imports

# third party imports
from scrapy import Field, Item


class UFCStatsFighterItem(Item):
    """
    Item class for fighter data from UFCStats
    """

    FIGHTER_ID = Field()
    FIGHTER_NAME = Field()
    HEIGHT_INCHES = Field()
    REACH_INCHES = Field()
    FIGHTING_STANCE = Field()
    DATE_OF_BIRTH = Field()


class UFCStatsBoutOverallItem(Item):
    """
    Item class for overall bout data from UFCStats
    """

    BOUT_ID = Field()

    # info from event page
    EVENT_ID = Field()
    EVENT_NAME = Field()
    DATE = Field()
    LOCATION = Field()
    BOUT_ORDINAL = Field()

    # Info from bout page
    RED_FIGHTER_ID = Field()
    BLUE_FIGHTER_ID = Field()
    RED_FIGHTER_NAME = Field()
    BLUE_FIGHTER_NAME = Field()
    RED_OUTCOME = Field()
    BLUE_OUTCOME = Field()
    BOUT_TYPE = Field()
    OUTCOME_METHOD = Field()
    OUTCOME_METHOD_DETAILS = Field()
    END_ROUND = Field()
    END_ROUND_TIME_MINUTES = Field()
    BOUT_TIME_FORMAT = Field()
    TOTAL_TIME_MINUTES = Field()

    # Overall
    RED_KNOCKDOWNS = Field()
    BLUE_KNOCKDOWNS = Field()
    RED_TOTAL_STRIKES_LANDED = Field()
    RED_TOTAL_STRIKES_ATTEMPTED = Field()
    BLUE_TOTAL_STRIKES_LANDED = Field()
    BLUE_TOTAL_STRIKES_ATTEMPTED = Field()
    RED_TAKEDOWNS_LANDED = Field()
    RED_TAKEDOWNS_ATTEMPTED = Field()
    BLUE_TAKEDOWNS_LANDED = Field()
    BLUE_TAKEDOWNS_ATTEMPTED = Field()
    RED_SUBMISSION_ATTEMPTS = Field()
    BLUE_SUBMISSION_ATTEMPTS = Field()
    RED_REVERSALS = Field()
    BLUE_REVERSALS = Field()
    RED_CONTROL_TIME_MINUTES = Field()
    BLUE_CONTROL_TIME_MINUTES = Field()
    RED_SIGNIFICANT_STRIKES_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_HEAD_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_BODY_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_BODY_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_LEG_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_LEG_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_CLINCH_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_GROUND_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED = Field()


class UFCStatsBoutRoundItem(Item):
    """
    Item class for round-by-round bout data from UFCStats
    """

    BOUT_ID = Field()
    EVENT_ID = Field()
    DATE = Field()
    BOUT_ORDINAL = Field()
    ROUND = Field()

    # Round stats
    RED_KNOCKDOWNS = Field()
    BLUE_KNOCKDOWNS = Field()
    RED_TOTAL_STRIKES_LANDED = Field()
    RED_TOTAL_STRIKES_ATTEMPTED = Field()
    BLUE_TOTAL_STRIKES_LANDED = Field()
    BLUE_TOTAL_STRIKES_ATTEMPTED = Field()
    RED_TAKEDOWNS_LANDED = Field()
    RED_TAKEDOWNS_ATTEMPTED = Field()
    BLUE_TAKEDOWNS_LANDED = Field()
    BLUE_TAKEDOWNS_ATTEMPTED = Field()
    RED_SUBMISSION_ATTEMPTS = Field()
    BLUE_SUBMISSION_ATTEMPTS = Field()
    RED_REVERSALS = Field()
    BLUE_REVERSALS = Field()
    RED_CONTROL_TIME_MINUTES = Field()
    BLUE_CONTROL_TIME_MINUTES = Field()
    RED_SIGNIFICANT_STRIKES_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_HEAD_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_BODY_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_BODY_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_LEG_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_LEG_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_CLINCH_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED = Field()
    RED_SIGNIFICANT_STRIKES_GROUND_LANDED = Field()
    RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED = Field()
    BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED = Field()
    BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED = Field()
