# standard library imports

# third party imports

# local imports


CREATE_UFCSTATS_FIGHTERS_TABLE = """
    CREATE TABLE IF NOT EXISTS UFCSTATS_FIGHTERS (
        FIGHTER_ID TEXT PRIMARY KEY,
        FIGHTER_NAME TEXT,
        HEIGHT_INCHES INTEGER,
        REACH_INCHES INTEGER,
        STANCE TEXT,
        DATE_OF_BIRTH DATE
    );
"""

CREATE_UFCSTATS_BOUTS_OVERALL_TABLE = """
    CREATE TABLE IF NOT EXISTS UFCSTATS_BOUTS_OVERALL (
        BOUT_ID TEXT PRIMARY KEY,
        EVENT_ID TEXT NOT NULL,
        EVENT_NAME TEXT,
        DATE DATE,
        LOCATION TEXT,
        BOUT_ORDINAL INTEGER,
        RED_FIGHTER_ID TEXT NOT NULL,
        BLUE_FIGHTER_ID TEXT NOT NULL,
        RED_OUTCOME TEXT,
        BLUE_OUTCOME TEXT,
        WEIGHT_CLASS TEXT,
        BOUT_LONGNAME TEXT,
        BOUT_PERF_BONUS TEXT,
        OUTCOME_METHOD TEXT,
        OUTCOME_METHOD_DETAILS TEXT,
        END_ROUND INTEGER,
        END_ROUND_TIME_SECONDS INTEGER,
        BOUT_TIME_FORMAT TEXT,
        TOTAL_TIME_SECONDS INTEGER
    );
"""

CREATE_UFCSTATS_BOUTS_BY_ROUND_TABLE = """
    CREATE TABLE IF NOT EXISTS UFCSTATS_BOUTS_BY_ROUND (
        BOUT_ROUND_ID TEXT PRIMARY KEY,
        BOUT_ID TEXT NOT NULL,
        ROUND INTEGER,
        TIME_FOUGHT_SECONDS INTEGER,
        RED_KNOCKDOWNS INTEGER,
        BLUE_KNOCKDOWNS INTEGER,
        RED_TOTAL_STRIKES_LANDED INTEGER,
        RED_TOTAL_STRIKES_ATTEMPTED INTEGER,
        BLUE_TOTAL_STRIKES_LANDED INTEGER,
        BLUE_TOTAL_STRIKES_ATTEMPTED INTEGER,
        RED_TAKEDOWNS_LANDED INTEGER,
        RED_TAKEDOWNS_ATTEMPTED INTEGER,
        BLUE_TAKEDOWNS_LANDED INTEGER,
        BLUE_TAKEDOWNS_ATTEMPTED INTEGER,
        RED_SUBMISSION_ATTEMPTS INTEGER,
        BLUE_SUBMISSION_ATTEMPTS INTEGER,
        RED_REVERSALS INTEGER,
        BLUE_REVERSALS INTEGER,
        RED_CONTROL_TIME_SECONDS INTEGER,
        BLUE_CONTROL_TIME_SECONDS INTEGER,
        RED_SIGNIFICANT_STRIKES_LANDED INTEGER,
        RED_SIGNIFICANT_STRIKES_ATTEMPTED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_LANDED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_ATTEMPTED INTEGER,
        RED_SIGNIFICANT_STRIKES_HEAD_LANDED INTEGER,
        RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED INTEGER,
        RED_SIGNIFICANT_STRIKES_BODY_LANDED INTEGER,
        RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_BODY_LANDED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED INTEGER,
        RED_SIGNIFICANT_STRIKES_LEG_LANDED INTEGER,
        RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_LEG_LANDED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED INTEGER,
        RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED INTEGER,
        RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED INTEGER,
        RED_SIGNIFICANT_STRIKES_CLINCH_LANDED INTEGER,
        RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED INTEGER,
        RED_SIGNIFICANT_STRIKES_GROUND_LANDED INTEGER,
        RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED INTEGER,
        BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED INTEGER
    );
"""

CREATE_FIGHTODDSIO_FIGHTERS_TABLE = """
    CREATE TABLE IF NOT EXISTS FIGHTODDSIO_FIGHTERS (
        FIGHTER_SLUG TEXT PRIMARY KEY,
        FIGHTER_NAME TEXT,
        HEIGHT_CENTIMETERS REAL,
        REACH_INCHES REAL,
        LEG_REACH_INCHES REAL,
        FIGHTING_STYLE TEXT,
        STANCE TEXT,
        NATIONALITY TEXT,
        DATE_OF_BIRTH DATE
    );
"""

CREATE_FIGHTODDSIO_BOUTS_TABLE = """
    CREATE TABLE IF NOT EXISTS FIGHTODDSIO_BOUTS (
        BOUT_SLUG TEXT PRIMARY KEY,
        EVENT_SLUG TEXT NOT NULL,
        EVENT_NAME TEXT,
        DATE DATE,
        LOCATION TEXT,
        VENUE TEXT,
        BOUT_ORDINAL INTEGER,
        BOUT_CARD_TYPE TEXT,
        WEIGHT_CLASS TEXT,
        WEIGHT INTEGER,
        FIGHTER_1_SLUG TEXT NOT NULL,
        FIGHTER_2_SLUG TEXT NOT NULL,
        WINNER_SLUG TEXT,
        OUTCOME_METHOD_1 TEXT,
        OUTCOME_METHOD_2 TEXT,
        END_ROUND INTEGER,
        END_ROUND_TIME_SECONDS INTEGER,
        TOTAL_TIME_SECONDS INTEGER,
        FIGHTER_1_ODDS INTEGER,
        FIGHTER_2_ODDS INTEGER
    );
"""
