# standard library imports

# third party imports

# local imports

STACKED_STATS_ALL_BOUTS_QUERY = """
WITH bout_stats_overall AS (
  SELECT 
    BOUT_ID, 
    SUM(RED_KNOCKDOWNS) AS RED_KNOCKDOWNS,
    SUM(BLUE_KNOCKDOWNS) AS BLUE_KNOCKDOWNS, 
    SUM(RED_TOTAL_STRIKES_LANDED) AS RED_TOTAL_STRIKES_LANDED, 
    SUM(RED_TOTAL_STRIKES_ATTEMPTED) AS RED_TOTAL_STRIKES_ATTEMPTED, 
    SUM(BLUE_TOTAL_STRIKES_LANDED) AS BLUE_TOTAL_STRIKES_LANDED, 
    SUM(BLUE_TOTAL_STRIKES_ATTEMPTED) AS BLUE_TOTAL_STRIKES_ATTEMPTED, 
    SUM(RED_TAKEDOWNS_LANDED) AS RED_TAKEDOWNS_LANDED, 
    SUM(RED_TAKEDOWNS_ATTEMPTED) AS RED_TAKEDOWNS_ATTEMPTED, 
    SUM(BLUE_TAKEDOWNS_LANDED) AS BLUE_TAKEDOWNS_LANDED, 
    SUM(BLUE_TAKEDOWNS_ATTEMPTED) AS BLUE_TAKEDOWNS_ATTEMPTED, 
    SUM(RED_SUBMISSION_ATTEMPTS) AS RED_SUBMISSION_ATTEMPTS, 
    SUM(BLUE_SUBMISSION_ATTEMPTS) AS BLUE_SUBMISSION_ATTEMPTS, 
    SUM(RED_REVERSALS) AS RED_REVERSALS, 
    SUM(BLUE_REVERSALS) AS BLUE_REVERSALS, 
    SUM(RED_CONTROL_TIME_SECONDS) AS RED_CONTROL_TIME_SECONDS, 
    SUM(BLUE_CONTROL_TIME_SECONDS) AS BLUE_CONTROL_TIME_SECONDS, 
    SUM(RED_SIGNIFICANT_STRIKES_LANDED) AS RED_SIGNIFICANT_STRIKES_LANDED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_ATTEMPTED
    ) AS RED_SIGNIFICANT_STRIKES_ATTEMPTED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_LANDED
    ) AS BLUE_SIGNIFICANT_STRIKES_LANDED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_ATTEMPTED
    ) AS BLUE_SIGNIFICANT_STRIKES_ATTEMPTED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_HEAD_LANDED
    ) AS RED_SIGNIFICANT_STRIKES_HEAD_LANDED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED
    ) AS RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED
    ) AS BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED
    ) AS BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_BODY_LANDED
    ) AS RED_SIGNIFICANT_STRIKES_BODY_LANDED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED
    ) AS RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_BODY_LANDED
    ) AS BLUE_SIGNIFICANT_STRIKES_BODY_LANDED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED
    ) AS BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_LEG_LANDED
    ) AS RED_SIGNIFICANT_STRIKES_LEG_LANDED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED
    ) AS RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_LEG_LANDED
    ) AS BLUE_SIGNIFICANT_STRIKES_LEG_LANDED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED
    ) AS BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED
    ) AS RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED
    ) AS RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED
    ) AS BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED
    ) AS BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_CLINCH_LANDED
    ) AS RED_SIGNIFICANT_STRIKES_CLINCH_LANDED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED
    ) AS RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED
    ) AS BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED
    ) AS BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_GROUND_LANDED
    ) AS RED_SIGNIFICANT_STRIKES_GROUND_LANDED, 
    SUM(
      RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED
    ) AS RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED
    ) AS BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED, 
    SUM(
      BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED
    ) AS BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED 
  FROM 
    UFCSTATS_BOUTS_BY_ROUND 
  GROUP BY 
    BOUT_ID
), 
bout_stats_round_1 AS (
  SELECT 
    BOUT_ID, 
    RED_KNOCKDOWNS AS RED_KNOCKDOWNS_ROUND_1, 
    BLUE_KNOCKDOWNS AS BLUE_KNOCKDOWNS_ROUND_1, 
    RED_TOTAL_STRIKES_LANDED AS RED_TOTAL_STRIKES_LANDED_ROUND_1, 
    RED_TOTAL_STRIKES_ATTEMPTED AS RED_TOTAL_STRIKES_ATTEMPTED_ROUND_1, 
    BLUE_TOTAL_STRIKES_LANDED AS BLUE_TOTAL_STRIKES_LANDED_ROUND_1, 
    BLUE_TOTAL_STRIKES_ATTEMPTED AS BLUE_TOTAL_STRIKES_ATTEMPTED_ROUND_1, 
    RED_TAKEDOWNS_LANDED AS RED_TAKEDOWNS_LANDED_ROUND_1, 
    RED_TAKEDOWNS_ATTEMPTED AS RED_TAKEDOWNS_ATTEMPTED_ROUND_1, 
    BLUE_TAKEDOWNS_LANDED AS BLUE_TAKEDOWNS_LANDED_ROUND_1, 
    BLUE_TAKEDOWNS_ATTEMPTED AS BLUE_TAKEDOWNS_ATTEMPTED_ROUND_1, 
    RED_SUBMISSION_ATTEMPTS AS RED_SUBMISSION_ATTEMPTS_ROUND_1, 
    BLUE_SUBMISSION_ATTEMPTS AS BLUE_SUBMISSION_ATTEMPTS_ROUND_1, 
    RED_REVERSALS AS RED_REVERSALS_ROUND_1, 
    BLUE_REVERSALS AS BLUE_REVERSALS_ROUND_1, 
    RED_CONTROL_TIME_SECONDS AS RED_CONTROL_TIME_SECONDS_ROUND_1, 
    BLUE_CONTROL_TIME_SECONDS AS BLUE_CONTROL_TIME_SECONDS_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_LANDED AS RED_SIGNIFICANT_STRIKES_LANDED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_ATTEMPTED AS RED_SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_LANDED AS BLUE_SIGNIFICANT_STRIKES_LANDED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_ATTEMPTED AS BLUE_SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_HEAD_LANDED AS RED_SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED AS RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED AS BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED AS BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_BODY_LANDED AS RED_SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED AS RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_BODY_LANDED AS BLUE_SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED AS BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_LEG_LANDED AS RED_SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED AS RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_LEG_LANDED AS BLUE_SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED AS BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED AS RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED AS RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED AS BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED AS BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_CLINCH_LANDED AS RED_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED AS RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED AS BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED AS BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_GROUND_LANDED AS RED_SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1, 
    RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED AS RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED AS BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1, 
    BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED AS BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1 
  FROM 
    UFCSTATS_BOUTS_BY_ROUND 
  WHERE 
    ROUND = 1
), 
bout_stats_with_meta AS (
  SELECT 
    * 
  FROM 
    UFCSTATS_BOUTS_OVERALL AS t1 
    LEFT JOIN bout_stats_overall AS t2 ON t1.BOUT_ID = t2.BOUT_ID 
    LEFT JOIN bout_stats_round_1 AS t3 ON t1.BOUT_ID = t3.BOUT_ID
    LEFT JOIN LOCATION_ELEVATIONS AS t4 ON t1.LOCATION = t4.LOCATION
) 
SELECT 
  BOUT_ID, 
  EVENT_ID, 
  DATE, 
  JULIANDAY(DATE) - JULIANDAY(DATE_OF_BIRTH) AS AGE_DAYS, 
  BOUT_ORDINAL, 
  LATITUDE,
  LONGITUDE,
  ELEVATION_METERS,
  RED_FIGHTER_ID AS FIGHTER_ID, 
  CASE RED_OUTCOME WHEN 'W' THEN 1 ELSE 0 END AS WIN, 
  CASE RED_OUTCOME WHEN 'L' THEN 1 ELSE 0 END AS LOSS, 
  CASE RED_OUTCOME WHEN 'D' THEN 1 ELSE 0 END AS DRAW, 
  CASE RED_OUTCOME WHEN 'NC' THEN 1 ELSE 0 END AS NO_CONTEST, 
  1 AS BOUT_FOUGHT, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) THEN 1 ELSE 0 END AS WIN_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' THEN 1 ELSE 0 END AS WIN_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD LIKE '%Decision%' THEN 1 ELSE 0 END AS WIN_BY_DECISION, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Decision - Unanimous' THEN 1 ELSE 0 END AS WIN_BY_DECISION_UNANIMOUS, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Decision - Majority' THEN 1 ELSE 0 END AS WIN_BY_DECISION_MAJORITY, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Decision - Split' THEN 1 ELSE 0 END AS WIN_BY_DECISION_SPLIT, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'DQ' THEN 1 ELSE 0 END AS WIN_BY_DQ, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) THEN 1 ELSE 0 END AS LOSS_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' THEN 1 ELSE 0 END AS LOSS_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD LIKE '%Decision%' THEN 1 ELSE 0 END AS LOSS_BY_DECISION, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Decision - Unanimous' THEN 1 ELSE 0 END AS LOSS_BY_DECISION_UNANIMOUS, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Decision - Majority' THEN 1 ELSE 0 END AS LOSS_BY_DECISION_MAJORITY, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Decision - Split' THEN 1 ELSE 0 END AS LOSS_BY_DECISION_SPLIT, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'DQ' THEN 1 ELSE 0 END AS LOSS_BY_DQ, 
  CASE WHEN BOUT_LONGNAME LIKE '%Title Bout%' 
  AND BOUT_LONGNAME NOT LIKE '%Tournament Title Bout%' THEN 1 ELSE 0 END AS TITLE_BOUT, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND BOUT_LONGNAME LIKE '%Title Bout%' 
  AND BOUT_LONGNAME NOT LIKE '%Tournament Title Bout%' THEN 1 ELSE 0 END AS WIN_TITLE, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND BOUT_LONGNAME LIKE '%Title Bout%' 
  AND BOUT_LONGNAME NOT LIKE '%Tournament Title Bout%' THEN 1 ELSE 0 END AS LOSS_TITLE, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND BOUT_PERF_BONUS = 1 THEN 1 ELSE 0 END AS PERFORMANCE_BONUS, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD IN (
    'KO/TKO', 'TKO - Doctor''s Stoppage', 
    'Submission'
  ) 
  AND (
    OUTCOME_METHOD_DETAILS LIKE '%Injury%' 
    OR OUTCOME_METHOD_DETAILS LIKE '%injury%'
  ) THEN 1 ELSE 0 END AS LOSS_INJURY, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS WIN_ROUND_1, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS WIN_ROUND_2, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS WIN_ROUND_3, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS WIN_ROUND_4, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS WIN_ROUND_5, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS LOSS_ROUND_1, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS LOSS_ROUND_2, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS LOSS_ROUND_3, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS LOSS_ROUND_4, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS LOSS_ROUND_5, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS WIN_ROUND_1_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS WIN_ROUND_2_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS WIN_ROUND_3_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS WIN_ROUND_4_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS WIN_ROUND_5_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS WIN_ROUND_1_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS WIN_ROUND_2_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS WIN_ROUND_3_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS WIN_ROUND_4_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS WIN_ROUND_5_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS LOSS_ROUND_1_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS LOSS_ROUND_2_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS LOSS_ROUND_3_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS LOSS_ROUND_4_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS LOSS_ROUND_5_BY_KO_TKO, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS LOSS_ROUND_1_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS LOSS_ROUND_2_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS LOSS_ROUND_3_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS LOSS_ROUND_4_BY_SUBMISSION, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS LOSS_ROUND_5_BY_SUBMISSION, 
  CASE BOUT_TIME_FORMAT WHEN '3 Rnd (5-5-5)' THEN 1 ELSE 0 END AS THREE_ROUND_FORMAT, 
  CASE BOUT_TIME_FORMAT WHEN '5 Rnd (5-5-5-5-5)' THEN 1 ELSE 0 END AS FIVE_ROUND_FORMAT, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND BOUT_TIME_FORMAT = '3 Rnd (5-5-5)' THEN 1 ELSE 0 END AS WIN_THREE_ROUND_FORMAT, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND BOUT_TIME_FORMAT = '3 Rnd (5-5-5)' THEN 1 ELSE 0 END AS LOSS_THREE_ROUND_FORMAT, 
  CASE WHEN RED_OUTCOME = 'W' 
  AND BOUT_TIME_FORMAT = '5 Rnd (5-5-5-5-5)' THEN 1 ELSE 0 END AS WIN_FIVE_ROUND_FORMAT, 
  CASE WHEN RED_OUTCOME = 'L' 
  AND BOUT_TIME_FORMAT = '5 Rnd (5-5-5-5-5)' THEN 1 ELSE 0 END AS LOSS_FIVE_ROUND_FORMAT, 
  TOTAL_TIME_SECONDS, 
  CASE WHEN END_ROUND = 1 THEN END_ROUND_TIME_SECONDS WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT = '1 Rnd + OT (12-3)' THEN 720 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT IN (
    '1 Rnd + OT (15-3)', '1 Rnd + 2OT (15-3-3)'
  ) THEN 900 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT = '1 Rnd + 2OT (24-3-3)' THEN 1440 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT = '1 Rnd + OT (27-3)' THEN 1620 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT IN (
    '1 Rnd + OT (30-3)', '1 Rnd + OT (30-5)'
  ) THEN 1800 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT = '1 Rnd + OT (31-5)' THEN 1860 ELSE 300 END AS ROUND_1_TIME_SECONDS, 
  CASE WHEN RED_OUTCOME = 'W' THEN TOTAL_TIME_SECONDS ELSE 0 END AS WIN_TOTAL_TIME_SECONDS, 
  CASE WHEN RED_OUTCOME = 'L' THEN TOTAL_TIME_SECONDS ELSE 0 END AS LOSS_TOTAL_TIME_SECONDS, 
  RED_KNOCKDOWNS AS KNOCKDOWNS, 
  RED_TOTAL_STRIKES_LANDED AS TOTAL_STRIKES_LANDED, 
  RED_TOTAL_STRIKES_ATTEMPTED AS TOTAL_STRIKES_ATTEMPTED, 
  RED_TAKEDOWNS_LANDED AS TAKEDOWNS_LANDED, 
  RED_TAKEDOWNS_ATTEMPTED AS TAKEDOWNS_ATTEMPTED, 
  RED_SUBMISSION_ATTEMPTS AS SUBMISSION_ATTEMPTS, 
  RED_REVERSALS AS REVERSALS, 
  RED_CONTROL_TIME_SECONDS AS CONTROL_TIME_SECONDS, 
  RED_SIGNIFICANT_STRIKES_LANDED AS SIGNIFICANT_STRIKES_LANDED, 
  RED_SIGNIFICANT_STRIKES_ATTEMPTED AS SIGNIFICANT_STRIKES_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_HEAD_LANDED AS SIGNIFICANT_STRIKES_HEAD_LANDED, 
  RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED AS SIGNIFICANT_STRIKES_HEAD_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_BODY_LANDED AS SIGNIFICANT_STRIKES_BODY_LANDED, 
  RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED AS SIGNIFICANT_STRIKES_BODY_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_LEG_LANDED AS SIGNIFICANT_STRIKES_LEG_LANDED, 
  RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED AS SIGNIFICANT_STRIKES_LEG_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED AS SIGNIFICANT_STRIKES_DISTANCE_LANDED, 
  RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED AS SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_CLINCH_LANDED AS SIGNIFICANT_STRIKES_CLINCH_LANDED, 
  RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED AS SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED, 
  (
    RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED + RED_SIGNIFICANT_STRIKES_CLINCH_LANDED
  ) AS SIGNIFICANT_STRIKES_STANDING_LANDED, 
  (
    RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED + RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED
  ) AS SIGNIFICANT_STRIKES_STANDING_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_GROUND_LANDED AS SIGNIFICANT_STRIKES_GROUND_LANDED, 
  RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED AS SIGNIFICANT_STRIKES_GROUND_ATTEMPTED, 
  BLUE_KNOCKDOWNS AS OPP_KNOCKDOWNS, 
  BLUE_TOTAL_STRIKES_LANDED AS OPP_TOTAL_STRIKES_LANDED, 
  BLUE_TOTAL_STRIKES_ATTEMPTED AS OPP_TOTAL_STRIKES_ATTEMPTED, 
  BLUE_TAKEDOWNS_LANDED AS OPP_TAKEDOWNS_LANDED, 
  BLUE_TAKEDOWNS_ATTEMPTED AS OPP_TAKEDOWNS_ATTEMPTED, 
  BLUE_SUBMISSION_ATTEMPTS AS OPP_SUBMISSION_ATTEMPTS, 
  BLUE_REVERSALS AS OPP_REVERSALS, 
  BLUE_CONTROL_TIME_SECONDS AS OPP_CONTROL_TIME_SECONDS, 
  BLUE_SIGNIFICANT_STRIKES_LANDED AS OPP_SIGNIFICANT_STRIKES_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED AS OPP_SIGNIFICANT_STRIKES_HEAD_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_BODY_LANDED AS OPP_SIGNIFICANT_STRIKES_BODY_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_BODY_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_LEG_LANDED AS OPP_SIGNIFICANT_STRIKES_LEG_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_LEG_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED AS OPP_SIGNIFICANT_STRIKES_DISTANCE_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED AS OPP_SIGNIFICANT_STRIKES_CLINCH_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED, 
  (
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED + BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED
  ) AS OPP_SIGNIFICANT_STRIKES_STANDING_LANDED, 
  (
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED + BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED
  ) AS OPP_SIGNIFICANT_STRIKES_STANDING_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED AS OPP_SIGNIFICANT_STRIKES_GROUND_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED, 
  RED_KNOCKDOWNS_ROUND_1 AS KNOCKDOWNS_ROUND_1, 
  RED_TOTAL_STRIKES_LANDED_ROUND_1 AS TOTAL_STRIKES_LANDED_ROUND_1, 
  RED_TOTAL_STRIKES_ATTEMPTED_ROUND_1 AS TOTAL_STRIKES_ATTEMPTED_ROUND_1, 
  RED_TAKEDOWNS_LANDED_ROUND_1 AS TAKEDOWNS_LANDED_ROUND_1, 
  RED_TAKEDOWNS_ATTEMPTED_ROUND_1 AS TAKEDOWNS_ATTEMPTED_ROUND_1, 
  RED_SUBMISSION_ATTEMPTS_ROUND_1 AS SUBMISSION_ATTEMPTS_ROUND_1, 
  RED_REVERSALS_ROUND_1 AS REVERSALS_ROUND_1, 
  RED_CONTROL_TIME_SECONDS_ROUND_1 AS CONTROL_TIME_SECONDS_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1, 
  (
    RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1 + RED_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1
  ) AS SIGNIFICANT_STRIKES_STANDING_LANDED_ROUND_1, 
  (
    RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1 + RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1
  ) AS SIGNIFICANT_STRIKES_STANDING_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1, 
  BLUE_KNOCKDOWNS_ROUND_1 AS OPP_KNOCKDOWNS_ROUND_1, 
  BLUE_TOTAL_STRIKES_LANDED_ROUND_1 AS OPP_TOTAL_STRIKES_LANDED_ROUND_1, 
  BLUE_TOTAL_STRIKES_ATTEMPTED_ROUND_1 AS OPP_TOTAL_STRIKES_ATTEMPTED_ROUND_1, 
  BLUE_TAKEDOWNS_LANDED_ROUND_1 AS OPP_TAKEDOWNS_LANDED_ROUND_1, 
  BLUE_TAKEDOWNS_ATTEMPTED_ROUND_1 AS OPP_TAKEDOWNS_ATTEMPTED_ROUND_1, 
  BLUE_SUBMISSION_ATTEMPTS_ROUND_1 AS OPP_SUBMISSION_ATTEMPTS_ROUND_1, 
  BLUE_REVERSALS_ROUND_1 AS OPP_REVERSALS_ROUND_1, 
  BLUE_CONTROL_TIME_SECONDS_ROUND_1 AS OPP_CONTROL_TIME_SECONDS_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1, 
  (
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1 + BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1
  ) AS OPP_SIGNIFICANT_STRIKES_STANDING_LANDED_ROUND_1, 
  (
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1 + BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1
  ) AS OPP_SIGNIFICANT_STRIKES_STANDING_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1, 
  0 AS RED_BLUE_ORDER 
FROM 
  bout_stats_with_meta AS t1 
  INNER JOIN UFCSTATS_FIGHTERS AS t2 ON t1.RED_FIGHTER_ID = t2.FIGHTER_ID 
UNION 
SELECT 
  BOUT_ID, 
  EVENT_ID, 
  DATE, 
  JULIANDAY(DATE) - JULIANDAY(DATE_OF_BIRTH) AS AGE_DAYS, 
  BOUT_ORDINAL, 
  LATITUDE,
  LONGITUDE,
  ELEVATION_METERS,
  BLUE_FIGHTER_ID AS FIGHTER_ID, 
  CASE BLUE_OUTCOME WHEN 'W' THEN 1 ELSE 0 END AS WIN, 
  CASE BLUE_OUTCOME WHEN 'L' THEN 1 ELSE 0 END AS LOSS, 
  CASE BLUE_OUTCOME WHEN 'D' THEN 1 ELSE 0 END AS DRAW, 
  CASE BLUE_OUTCOME WHEN 'NC' THEN 1 ELSE 0 END AS NO_CONTEST, 
  1 AS BOUT_FOUGHT, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) THEN 1 ELSE 0 END AS WIN_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' THEN 1 ELSE 0 END AS WIN_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD LIKE '%Decision%' THEN 1 ELSE 0 END AS WIN_BY_DECISION, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Decision - Unanimous' THEN 1 ELSE 0 END AS WIN_BY_DECISION_UNANIMOUS, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Decision - Majority' THEN 1 ELSE 0 END AS WIN_BY_DECISION_MAJORITY, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Decision - Split' THEN 1 ELSE 0 END AS WIN_BY_DECISION_SPLIT, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'DQ' THEN 1 ELSE 0 END AS WIN_BY_DQ, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) THEN 1 ELSE 0 END AS LOSS_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' THEN 1 ELSE 0 END AS LOSS_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD LIKE '%Decision%' THEN 1 ELSE 0 END AS LOSS_BY_DECISION, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Decision - Unanimous' THEN 1 ELSE 0 END AS LOSS_BY_DECISION_UNANIMOUS, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Decision - Majority' THEN 1 ELSE 0 END AS LOSS_BY_DECISION_MAJORITY, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Decision - Split' THEN 1 ELSE 0 END AS LOSS_BY_DECISION_SPLIT, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'DQ' THEN 1 ELSE 0 END AS LOSS_BY_DQ, 
  CASE WHEN BOUT_LONGNAME LIKE '%Title Bout%' 
  AND BOUT_LONGNAME NOT LIKE '%Tournament Title Bout%' THEN 1 ELSE 0 END AS TITLE_BOUT, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND BOUT_LONGNAME LIKE '%Title Bout%' 
  AND BOUT_LONGNAME NOT LIKE '%Tournament Title Bout%' THEN 1 ELSE 0 END AS WIN_TITLE, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND BOUT_LONGNAME LIKE '%Title Bout%' 
  AND BOUT_LONGNAME NOT LIKE '%Tournament Title Bout%' THEN 1 ELSE 0 END AS LOSS_TITLE, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND BOUT_PERF_BONUS = 1 THEN 1 ELSE 0 END AS PERFORMANCE_BONUS, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD IN (
    'KO/TKO', 'TKO - Doctor''s Stoppage', 
    'Submission'
  ) 
  AND (
    OUTCOME_METHOD_DETAILS LIKE '%Injury%' 
    OR OUTCOME_METHOD_DETAILS LIKE '%injury%'
  ) THEN 1 ELSE 0 END AS LOSS_INJURY, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS WIN_ROUND_1, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS WIN_ROUND_2, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS WIN_ROUND_3, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS WIN_ROUND_4, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS WIN_ROUND_5, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS LOSS_ROUND_1, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS LOSS_ROUND_2, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS LOSS_ROUND_3, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS LOSS_ROUND_4, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS LOSS_ROUND_5, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS WIN_ROUND_1_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS WIN_ROUND_2_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS WIN_ROUND_3_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS WIN_ROUND_4_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS WIN_ROUND_5_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS WIN_ROUND_1_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS WIN_ROUND_2_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS WIN_ROUND_3_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS WIN_ROUND_4_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS WIN_ROUND_5_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS LOSS_ROUND_1_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS LOSS_ROUND_2_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS LOSS_ROUND_3_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS LOSS_ROUND_4_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND (
    OUTCOME_METHOD = 'KO/TKO' 
    OR OUTCOME_METHOD = 'TKO - Doctor''s Stoppage'
  ) 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS LOSS_ROUND_5_BY_KO_TKO, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 1 THEN 1 ELSE 0 END AS LOSS_ROUND_1_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 2 THEN 1 ELSE 0 END AS LOSS_ROUND_2_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 3 THEN 1 ELSE 0 END AS LOSS_ROUND_3_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 4 THEN 1 ELSE 0 END AS LOSS_ROUND_4_BY_SUBMISSION, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND OUTCOME_METHOD = 'Submission' 
  AND END_ROUND = 5 THEN 1 ELSE 0 END AS LOSS_ROUND_5_BY_SUBMISSION, 
  CASE BOUT_TIME_FORMAT WHEN '3 Rnd (5-5-5)' THEN 1 ELSE 0 END AS THREE_ROUND_FORMAT, 
  CASE BOUT_TIME_FORMAT WHEN '5 Rnd (5-5-5-5-5)' THEN 1 ELSE 0 END AS FIVE_ROUND_FORMAT, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND BOUT_TIME_FORMAT = '3 Rnd (5-5-5)' THEN 1 ELSE 0 END AS WIN_THREE_ROUND_FORMAT, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND BOUT_TIME_FORMAT = '3 Rnd (5-5-5)' THEN 1 ELSE 0 END AS LOSS_THREE_ROUND_FORMAT, 
  CASE WHEN BLUE_OUTCOME = 'W' 
  AND BOUT_TIME_FORMAT = '5 Rnd (5-5-5-5-5)' THEN 1 ELSE 0 END AS WIN_FIVE_ROUND_FORMAT, 
  CASE WHEN BLUE_OUTCOME = 'L' 
  AND BOUT_TIME_FORMAT = '5 Rnd (5-5-5-5-5)' THEN 1 ELSE 0 END AS LOSS_FIVE_ROUND_FORMAT, 
  TOTAL_TIME_SECONDS, 
  CASE WHEN END_ROUND = 1 THEN END_ROUND_TIME_SECONDS WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT = '1 Rnd + OT (12-3)' THEN 720 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT IN (
    '1 Rnd + OT (15-3)', '1 Rnd + 2OT (15-3-3)'
  ) THEN 900 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT = '1 Rnd + 2OT (24-3-3)' THEN 1440 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT = '1 Rnd + OT (27-3)' THEN 1620 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT IN (
    '1 Rnd + OT (30-3)', '1 Rnd + OT (30-5)'
  ) THEN 1800 WHEN END_ROUND != 1 
  AND BOUT_TIME_FORMAT = '1 Rnd + OT (31-5)' THEN 1860 ELSE 300 END AS ROUND_1_TIME_SECONDS, 
  CASE WHEN BLUE_OUTCOME = 'W' THEN TOTAL_TIME_SECONDS ELSE 0 END AS WIN_TOTAL_TIME_SECONDS, 
  CASE WHEN BLUE_OUTCOME = 'L' THEN TOTAL_TIME_SECONDS ELSE 0 END AS LOSS_TOTAL_TIME_SECONDS, 
  BLUE_KNOCKDOWNS AS KNOCKDOWNS, 
  BLUE_TOTAL_STRIKES_LANDED AS TOTAL_STRIKES_LANDED, 
  BLUE_TOTAL_STRIKES_ATTEMPTED AS TOTAL_STRIKES_ATTEMPTED, 
  BLUE_TAKEDOWNS_LANDED AS TAKEDOWNS_LANDED, 
  BLUE_TAKEDOWNS_ATTEMPTED AS TAKEDOWNS_ATTEMPTED, 
  BLUE_SUBMISSION_ATTEMPTS AS SUBMISSION_ATTEMPTS, 
  BLUE_REVERSALS AS REVERSALS, 
  BLUE_CONTROL_TIME_SECONDS AS CONTROL_TIME_SECONDS, 
  BLUE_SIGNIFICANT_STRIKES_LANDED AS SIGNIFICANT_STRIKES_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_ATTEMPTED AS SIGNIFICANT_STRIKES_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED AS SIGNIFICANT_STRIKES_HEAD_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED AS SIGNIFICANT_STRIKES_HEAD_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_BODY_LANDED AS SIGNIFICANT_STRIKES_BODY_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED AS SIGNIFICANT_STRIKES_BODY_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_LEG_LANDED AS SIGNIFICANT_STRIKES_LEG_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED AS SIGNIFICANT_STRIKES_LEG_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED AS SIGNIFICANT_STRIKES_DISTANCE_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED AS SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED AS SIGNIFICANT_STRIKES_CLINCH_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED AS SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED, 
  (
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED + BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED
  ) AS SIGNIFICANT_STRIKES_STANDING_LANDED, 
  (
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED + BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED
  ) AS SIGNIFICANT_STRIKES_STANDING_ATTEMPTED, 
  BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED AS SIGNIFICANT_STRIKES_GROUND_LANDED, 
  BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED AS SIGNIFICANT_STRIKES_GROUND_ATTEMPTED, 
  RED_KNOCKDOWNS AS OPP_KNOCKDOWNS, 
  RED_TOTAL_STRIKES_LANDED AS OPP_TOTAL_STRIKES_LANDED, 
  RED_TOTAL_STRIKES_ATTEMPTED AS OPP_TOTAL_STRIKES_ATTEMPTED, 
  RED_TAKEDOWNS_LANDED AS OPP_TAKEDOWNS_LANDED, 
  RED_TAKEDOWNS_ATTEMPTED AS OPP_TAKEDOWNS_ATTEMPTED, 
  RED_SUBMISSION_ATTEMPTS AS OPP_SUBMISSION_ATTEMPTS, 
  RED_REVERSALS AS OPP_REVERSALS, 
  RED_CONTROL_TIME_SECONDS AS OPP_CONTROL_TIME_SECONDS, 
  RED_SIGNIFICANT_STRIKES_LANDED AS OPP_SIGNIFICANT_STRIKES_LANDED, 
  RED_SIGNIFICANT_STRIKES_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_HEAD_LANDED AS OPP_SIGNIFICANT_STRIKES_HEAD_LANDED, 
  RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_BODY_LANDED AS OPP_SIGNIFICANT_STRIKES_BODY_LANDED, 
  RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_BODY_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_LEG_LANDED AS OPP_SIGNIFICANT_STRIKES_LEG_LANDED, 
  RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_LEG_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED AS OPP_SIGNIFICANT_STRIKES_DISTANCE_LANDED, 
  RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_CLINCH_LANDED AS OPP_SIGNIFICANT_STRIKES_CLINCH_LANDED, 
  RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED, 
  (
    RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED + RED_SIGNIFICANT_STRIKES_CLINCH_LANDED
  ) AS OPP_SIGNIFICANT_STRIKES_STANDING_LANDED, 
  (
    RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED + RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED
  ) AS OPP_SIGNIFICANT_STRIKES_STANDING_ATTEMPTED, 
  RED_SIGNIFICANT_STRIKES_GROUND_LANDED AS OPP_SIGNIFICANT_STRIKES_GROUND_LANDED, 
  RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED AS OPP_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED, 
  BLUE_KNOCKDOWNS_ROUND_1 AS KNOCKDOWNS_ROUND_1, 
  BLUE_TOTAL_STRIKES_LANDED_ROUND_1 AS TOTAL_STRIKES_LANDED_ROUND_1, 
  BLUE_TOTAL_STRIKES_ATTEMPTED_ROUND_1 AS TOTAL_STRIKES_ATTEMPTED_ROUND_1, 
  BLUE_TAKEDOWNS_LANDED_ROUND_1 AS TAKEDOWNS_LANDED_ROUND_1, 
  BLUE_TAKEDOWNS_ATTEMPTED_ROUND_1 AS TAKEDOWNS_ATTEMPTED_ROUND_1, 
  BLUE_SUBMISSION_ATTEMPTS_ROUND_1 AS SUBMISSION_ATTEMPTS_ROUND_1, 
  BLUE_REVERSALS_ROUND_1 AS REVERSALS_ROUND_1, 
  BLUE_CONTROL_TIME_SECONDS_ROUND_1 AS CONTROL_TIME_SECONDS_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1, 
  (
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1 + BLUE_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1
  ) AS SIGNIFICANT_STRIKES_STANDING_LANDED_ROUND_1, 
  (
    BLUE_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1 + BLUE_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1
  ) AS SIGNIFICANT_STRIKES_STANDING_ATTEMPTED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1 AS SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1, 
  BLUE_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1 AS SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1, 
  RED_KNOCKDOWNS_ROUND_1 AS OPP_KNOCKDOWNS_ROUND_1, 
  RED_TOTAL_STRIKES_LANDED_ROUND_1 AS OPP_TOTAL_STRIKES_LANDED_ROUND_1, 
  RED_TOTAL_STRIKES_ATTEMPTED_ROUND_1 AS OPP_TOTAL_STRIKES_ATTEMPTED_ROUND_1, 
  RED_TAKEDOWNS_LANDED_ROUND_1 AS OPP_TAKEDOWNS_LANDED_ROUND_1, 
  RED_TAKEDOWNS_ATTEMPTED_ROUND_1 AS OPP_TAKEDOWNS_ATTEMPTED_ROUND_1, 
  RED_SUBMISSION_ATTEMPTS_ROUND_1 AS OPP_SUBMISSION_ATTEMPTS_ROUND_1, 
  RED_REVERSALS_ROUND_1 AS OPP_REVERSALS_ROUND_1, 
  RED_CONTROL_TIME_SECONDS_ROUND_1 AS OPP_CONTROL_TIME_SECONDS_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_HEAD_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_HEAD_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_BODY_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_BODY_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_LEG_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_LEG_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1, 
  (
    RED_SIGNIFICANT_STRIKES_DISTANCE_LANDED_ROUND_1 + RED_SIGNIFICANT_STRIKES_CLINCH_LANDED_ROUND_1
  ) AS OPP_SIGNIFICANT_STRIKES_STANDING_LANDED_ROUND_1, 
  (
    RED_SIGNIFICANT_STRIKES_DISTANCE_ATTEMPTED_ROUND_1 + RED_SIGNIFICANT_STRIKES_CLINCH_ATTEMPTED_ROUND_1
  ) AS OPP_SIGNIFICANT_STRIKES_STANDING_ATTEMPTED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_GROUND_LANDED_ROUND_1, 
  RED_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1 AS OPP_SIGNIFICANT_STRIKES_GROUND_ATTEMPTED_ROUND_1, 
  1 AS RED_BLUE_ORDER 
FROM 
  bout_stats_with_meta AS t1 
  INNER JOIN UFCSTATS_FIGHTERS AS t2 ON t1.BLUE_FIGHTER_ID = t2.FIGHTER_ID 
ORDER BY 
  DATE, 
  EVENT_ID, 
  BOUT_ORDINAL, 
  RED_BLUE_ORDER;
"""
