# standard library imports

# third party imports

# local imports

PRELIMINARY_WIDE_MATCHING_QUERY = """
WITH cte1 AS (
  SELECT 
    MIN(FIGHTER_ID) AS FIGHTER_ID, 
    FIGHTER_NAME
  FROM 
    UFCSTATS_FIGHTERS 
  GROUP BY 
    FIGHTER_NAME
  HAVING 
    COUNT(FIGHTER_NAME) = 1
), 
cte2 AS (
  SELECT 
    MIN(FIGHTER_SLUG) AS FIGHTER_SLUG, 
    fighter_name 
  FROM 
    FIGHTODDSIO_FIGHTERS 
  GROUP BY 
    FIGHTER_NAME
  HAVING 
    COUNT(FIGHTER_NAME) = 1
)
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  UFCSTATS_FIGHTERS AS t1 
  INNER JOIN FIGHTODDSIO_FIGHTERS AS t2 ON (
    t1.FIGHTER_NAME = t2.FIGHTER_NAME 
    AND t1.FIGHTER_NICKNAME = t2.FIGHTER_NICKNAME
  )
UNION 
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  UFCSTATS_FIGHTERS AS t1 
  INNER JOIN FIGHTODDSIO_FIGHTERS AS t2 ON (
    t1.FIGHTER_NAME = t2.FIGHTER_NAME 
    AND t1.DATE_OF_BIRTH = t2.DATE_OF_BIRTH
  )
UNION 
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  UFCSTATS_FIGHTERS AS t1 
  INNER JOIN FIGHTODDSIO_FIGHTERS AS t2 ON (
    t1.FIGHTER_NICKNAME = t2.FIGHTER_NICKNAME
    AND t1.DATE_OF_BIRTH = t2.DATE_OF_BIRTH
  )
UNION 
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  cte1 AS t1 
  INNER JOIN cte2 AS t2 ON (
    t1.FIGHTER_NAME = t2.FIGHTER_NAME
  );
"""

MATCHING_QUERY_UPCOMING_BOUTS = """
WITH unmatched_ufcstats AS (
  SELECT 
    RED_FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
    DATE, 
    t3.FIGHTODDSIO_FIGHTER_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    UFCSTATS_UPCOMING AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.BLUE_FIGHTER_ID = t3.UFCSTATS_FIGHTER_ID 
  WHERE 
    t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL 
    AND t3.FIGHTODDSIO_FIGHTER_SLUG IS NOT NULL 
  UNION 
  SELECT 
    BLUE_FIGHTER_ID AS FIGHTER_ID, 
    DATE, 
    t2.FIGHTODDSIO_FIGHTER_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    UFCSTATS_UPCOMING AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.BLUE_FIGHTER_ID = t3.UFCSTATS_FIGHTER_ID 
  WHERE 
    t3.FIGHTODDSIO_FIGHTER_SLUG IS NULL 
    AND t2.FIGHTODDSIO_FIGHTER_SLUG IS NOT NULL
), 
unmatched_fightoddsio AS (
  SELECT 
    FIGHTER_1_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
    DATE, 
    FIGHTER_2_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    FIGHTODDSIO_UPCOMING AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTODDSIO_FIGHTER_SLUG 
  WHERE 
    t2.UFCSTATS_FIGHTER_ID IS NULL 
    AND t3.UFCSTATS_FIGHTER_ID IS NOT NULL 
  UNION 
  SELECT 
    FIGHTER_2_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
    DATE, 
    FIGHTER_1_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    FIGHTODDSIO_UPCOMING AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTODDSIO_FIGHTER_SLUG 
  WHERE 
    t3.UFCSTATS_FIGHTER_ID IS NULL 
    AND t2.UFCSTATS_FIGHTER_ID IS NOT NULL
) 
SELECT 
  UFCSTATS_FIGHTER_ID, 
  FIGHTODDSIO_FIGHTER_SLUG 
FROM 
  unmatched_ufcstats AS t1 
  LEFT JOIN unmatched_fightoddsio AS t2 ON t1.DATE = t2.DATE 
  AND t1.KNOWN_OPPONENT_SLUG = t2.KNOWN_OPPONENT_SLUG;
"""

MATCHING_QUERY_COMPLETED_BOUTS_STRICT = """
WITH latest_bout_dates_by_fighter AS (
  SELECT 
    FIGHTER_ID, 
    MAX(DATE) AS latest_date 
  FROM 
    (
      SELECT 
        RED_FIGHTER_ID AS FIGHTER_ID, 
        DATE 
      FROM 
        UFCSTATS_BOUTS_OVERALL 
      UNION 
      SELECT 
        BLUE_FIGHTER_ID AS FIGHTER_ID, 
        DATE 
      FROM 
        UFCSTATS_BOUTS_OVERALL
    ) 
  GROUP BY 
    FIGHTER_ID
), 
unmatched_ufcstats AS (
  SELECT 
    RED_FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
    DATE, 
    t3.FIGHTODDSIO_FIGHTER_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    UFCSTATS_BOUTS_OVERALL AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.BLUE_FIGHTER_ID = t3.UFCSTATS_FIGHTER_ID 
    INNER JOIN latest_bout_dates_by_fighter AS t4 ON t1.RED_FIGHTER_ID = t4.FIGHTER_ID 
    AND t1.DATE = t4.latest_date 
  WHERE 
    t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL 
    AND t3.FIGHTODDSIO_FIGHTER_SLUG IS NOT NULL 
  UNION 
  SELECT 
    BLUE_FIGHTER_ID AS FIGHTER_ID, 
    DATE, 
    t2.FIGHTODDSIO_FIGHTER_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    UFCSTATS_BOUTS_OVERALL AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.BLUE_FIGHTER_ID = t3.UFCSTATS_FIGHTER_ID 
    INNER JOIN latest_bout_dates_by_fighter AS t4 ON t1.BLUE_FIGHTER_ID = t4.FIGHTER_ID 
    AND t1.DATE = t4.latest_date 
  WHERE 
    t3.FIGHTODDSIO_FIGHTER_SLUG IS NULL 
    AND t2.FIGHTODDSIO_FIGHTER_SLUG IS NOT NULL
), 
unmatched_fightoddsio AS (
  SELECT 
    FIGHTER_1_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
    DATE, 
    FIGHTER_2_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    FIGHTODDSIO_BOUTS AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTODDSIO_FIGHTER_SLUG 
  WHERE 
    t2.UFCSTATS_FIGHTER_ID IS NULL 
    AND t3.UFCSTATS_FIGHTER_ID IS NOT NULL 
  UNION 
  SELECT 
    FIGHTER_2_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
    DATE, 
    FIGHTER_1_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    FIGHTODDSIO_BOUTS AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTODDSIO_FIGHTER_SLUG 
  WHERE 
    t3.UFCSTATS_FIGHTER_ID IS NULL 
    AND t2.UFCSTATS_FIGHTER_ID IS NOT NULL
) 
SELECT 
  UFCSTATS_FIGHTER_ID, 
  FIGHTODDSIO_FIGHTER_SLUG 
FROM 
  unmatched_ufcstats AS t1 
  LEFT JOIN unmatched_fightoddsio AS t2 ON t1.DATE = t2.DATE 
  AND t1.KNOWN_OPPONENT_SLUG = t2.KNOWN_OPPONENT_SLUG;
"""

MATCHING_QUERY_COMPLETED_BOUTS_LOOSE = """
WITH unmatched_ufcstats AS (
  SELECT 
    RED_FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
    DATE, 
    t3.FIGHTODDSIO_FIGHTER_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    UFCSTATS_BOUTS_OVERALL AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.BLUE_FIGHTER_ID = t3.UFCSTATS_FIGHTER_ID 
  WHERE 
    t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL 
    AND t3.FIGHTODDSIO_FIGHTER_SLUG IS NOT NULL 
  UNION 
  SELECT 
    BLUE_FIGHTER_ID AS FIGHTER_ID, 
    DATE, 
    t2.FIGHTODDSIO_FIGHTER_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    UFCSTATS_BOUTS_OVERALL AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.BLUE_FIGHTER_ID = t3.UFCSTATS_FIGHTER_ID 
  WHERE 
    t3.FIGHTODDSIO_FIGHTER_SLUG IS NULL 
    AND t2.FIGHTODDSIO_FIGHTER_SLUG IS NOT NULL
), 
unmatched_fightoddsio AS (
  SELECT 
    FIGHTER_1_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
    DATE, 
    FIGHTER_2_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    FIGHTODDSIO_BOUTS AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTODDSIO_FIGHTER_SLUG 
  WHERE 
    t2.UFCSTATS_FIGHTER_ID IS NULL 
    AND t3.UFCSTATS_FIGHTER_ID IS NOT NULL 
  UNION 
  SELECT 
    FIGHTER_2_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
    DATE, 
    FIGHTER_1_SLUG AS KNOWN_OPPONENT_SLUG 
  FROM 
    FIGHTODDSIO_BOUTS AS t1 
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
    LEFT JOIN FIGHTER_LINKAGE AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTODDSIO_FIGHTER_SLUG 
  WHERE 
    t3.UFCSTATS_FIGHTER_ID IS NULL 
    AND t2.UFCSTATS_FIGHTER_ID IS NOT NULL
) 
SELECT 
  UFCSTATS_FIGHTER_ID, 
  FIGHTODDSIO_FIGHTER_SLUG 
FROM 
  unmatched_ufcstats AS t1 
  LEFT JOIN unmatched_fightoddsio AS t2 ON t1.DATE = t2.DATE 
  AND t1.KNOWN_OPPONENT_SLUG = t2.KNOWN_OPPONENT_SLUG;
"""

CLEAN_UP_QUERY_COMPLETED_BOUTS = """
WITH unmatched_ufcstats_completed AS (
  SELECT
  	t3.*
  from
  	UFCSTATS_BOUTS_OVERALL AS t1
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID
    LEFT JOIN UFCSTATS_FIGHTERS AS t3 ON t1.RED_FIGHTER_ID = t3.FIGHTER_ID
  WHERE
    t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL
  UNION
  SELECT
  	t3.*
  from
  	UFCSTATS_BOUTS_OVERALL AS t1
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.BLUE_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID
    LEFT JOIN UFCSTATS_FIGHTERS AS t3 ON t1.BLUE_FIGHTER_ID = t3.FIGHTER_ID
  WHERE
    t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL
),
unmatched_fightoddsio_completed AS (
  SELECT
    t3.*
  FROM
    FIGHTODDSIO_BOUTS AS t1
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG
    LEFT JOIN FIGHTODDSIO_FIGHTERS AS t3 ON t1.FIGHTER_1_SLUG = t3.FIGHTER_SLUG
  WHERE
    t2.UFCSTATS_FIGHTER_ID IS NULL
  UNION
  SELECT
    t3.*
  FROM
    FIGHTODDSIO_BOUTS AS t1
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_2_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG
    LEFT JOIN FIGHTODDSIO_FIGHTERS AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTER_SLUG
  WHERE
    t2.UFCSTATS_FIGHTER_ID IS NULL
),
cte1 AS (
  SELECT 
    MIN(FIGHTER_ID) AS FIGHTER_ID, 
    FIGHTER_NAME
  FROM 
    unmatched_ufcstats_completed 
  GROUP BY 
    FIGHTER_NAME
  HAVING 
    COUNT(FIGHTER_NAME) = 1
), 
cte2 AS (
  SELECT 
    MIN(FIGHTER_SLUG) AS FIGHTER_SLUG, 
    fighter_name 
  FROM 
    unmatched_fightoddsio_completed 
  GROUP BY 
    FIGHTER_NAME
  HAVING 
    COUNT(FIGHTER_NAME) = 1
)
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  unmatched_ufcstats_completed AS t1 
  INNER JOIN unmatched_fightoddsio_completed AS t2 ON (
    t1.FIGHTER_NAME = t2.FIGHTER_NAME 
    AND t1.FIGHTER_NICKNAME = t2.FIGHTER_NICKNAME
  )
UNION 
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  unmatched_ufcstats_completed AS t1 
  INNER JOIN unmatched_fightoddsio_completed AS t2 ON (
    t1.FIGHTER_NAME = t2.FIGHTER_NAME 
    AND t1.DATE_OF_BIRTH = t2.DATE_OF_BIRTH
  )
UNION 
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  unmatched_ufcstats_completed AS t1 
  INNER JOIN unmatched_fightoddsio_completed AS t2 ON (
    t1.FIGHTER_NICKNAME = t2.FIGHTER_NICKNAME
    AND t1.DATE_OF_BIRTH = t2.DATE_OF_BIRTH
  )
UNION 
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  cte1 AS t1 
  INNER JOIN cte2 AS t2 ON (
    t1.FIGHTER_NAME = t2.FIGHTER_NAME
  );
"""

CLEAN_UP_QUERY_UPCOMING_BOUTS = """
WITH unmatched_ufcstats_upcoming AS (
  SELECT
  	t3.*
  from
  	UFCSTATS_UPCOMING AS t1
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID
    LEFT JOIN UFCSTATS_FIGHTERS AS t3 ON t1.RED_FIGHTER_ID = t3.FIGHTER_ID
  WHERE
    t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL
  UNION
  SELECT
  	t3.*
  from
  	UFCSTATS_UPCOMING AS t1
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.BLUE_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID
    LEFT JOIN UFCSTATS_FIGHTERS AS t3 ON t1.BLUE_FIGHTER_ID = t3.FIGHTER_ID
  WHERE
    t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL
),
unmatched_fightoddsio_upcoming AS (
  SELECT
    t3.*
  FROM
    FIGHTODDSIO_UPCOMING AS t1
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG
    LEFT JOIN FIGHTODDSIO_FIGHTERS AS t3 ON t1.FIGHTER_1_SLUG = t3.FIGHTER_SLUG
  WHERE
    t2.UFCSTATS_FIGHTER_ID IS NULL
  UNION
  SELECT
    t3.*
  FROM
    FIGHTODDSIO_UPCOMING AS t1
    LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_2_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG
    LEFT JOIN FIGHTODDSIO_FIGHTERS AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTER_SLUG
  WHERE
    t2.UFCSTATS_FIGHTER_ID IS NULL
),
cte1 AS (
  SELECT 
    MIN(FIGHTER_ID) AS FIGHTER_ID, 
    FIGHTER_NAME
  FROM 
    unmatched_ufcstats_upcoming 
  GROUP BY 
    FIGHTER_NAME
  HAVING 
    COUNT(FIGHTER_NAME) = 1
), 
cte2 AS (
  SELECT 
    MIN(FIGHTER_SLUG) AS FIGHTER_SLUG, 
    fighter_name 
  FROM 
    unmatched_fightoddsio_upcoming 
  GROUP BY 
    FIGHTER_NAME
  HAVING 
    COUNT(FIGHTER_NAME) = 1
)
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  unmatched_ufcstats_upcoming AS t1 
  INNER JOIN unmatched_fightoddsio_upcoming AS t2 ON (
    t1.FIGHTER_NAME = t2.FIGHTER_NAME 
    AND t1.FIGHTER_NICKNAME = t2.FIGHTER_NICKNAME
  )
UNION 
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  unmatched_ufcstats_upcoming AS t1 
  INNER JOIN unmatched_fightoddsio_upcoming AS t2 ON (
    t1.FIGHTER_NAME = t2.FIGHTER_NAME 
    AND t1.DATE_OF_BIRTH = t2.DATE_OF_BIRTH
  )
UNION 
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  unmatched_ufcstats_upcoming AS t1 
  INNER JOIN unmatched_fightoddsio_upcoming AS t2 ON (
    t1.FIGHTER_NICKNAME = t2.FIGHTER_NICKNAME
    AND t1.DATE_OF_BIRTH = t2.DATE_OF_BIRTH
  )
UNION 
SELECT 
  t1.FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  t2.FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG
FROM 
  cte1 AS t1 
  INNER JOIN cte2 AS t2 ON (
    t1.FIGHTER_NAME = t2.FIGHTER_NAME
  );
"""

UNKNOWN_UFCSTATS_UPCOMING_BOUTS = """
SELECT 
  FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  FIGHTER_NAME 
FROM 
  UFCSTATS_UPCOMING AS t1 
  LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
  LEFT JOIN UFCSTATS_FIGHTERS AS t3 ON t1.RED_FIGHTER_ID = t3.FIGHTER_ID 
WHERE 
  t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL 
UNION 
SELECT 
  FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  FIGHTER_NAME 
FROM 
  UFCSTATS_UPCOMING AS t1 
  LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.BLUE_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
  LEFT JOIN UFCSTATS_FIGHTERS AS t3 ON t1.BLUE_FIGHTER_ID = t3.FIGHTER_ID 
WHERE 
  t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL;
"""

UNKNOWN_FIGHTODDSIO_UPCOMING_BOUTS = """
SELECT 
  FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
  FIGHTER_NAME 
FROM 
  FIGHTODDSIO_UPCOMING AS t1 
  LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
  LEFT JOIN FIGHTODDSIO_FIGHTERS AS t3 ON t1.FIGHTER_1_SLUG = t3.FIGHTER_SLUG 
WHERE 
  t2.UFCSTATS_FIGHTER_ID IS NULL 
UNION 
SELECT 
  FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
  FIGHTER_NAME 
FROM 
  FIGHTODDSIO_UPCOMING AS t1 
  LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_2_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
  LEFT JOIN FIGHTODDSIO_FIGHTERS AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTER_SLUG 
WHERE 
  t2.UFCSTATS_FIGHTER_ID IS NULL;
"""

UNKNOWN_UFCSTATS_COMPLETED_BOUTS = """
SELECT 
  FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  FIGHTER_NAME 
FROM 
  UFCSTATS_BOUTS_OVERALL AS t1 
  LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.RED_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
  LEFT JOIN UFCSTATS_FIGHTERS AS t3 ON t1.RED_FIGHTER_ID = t3.FIGHTER_ID 
WHERE 
  t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL 
UNION 
SELECT 
  FIGHTER_ID AS UFCSTATS_FIGHTER_ID, 
  FIGHTER_NAME 
FROM 
  UFCSTATS_BOUTS_OVERALL AS t1 
  LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.BLUE_FIGHTER_ID = t2.UFCSTATS_FIGHTER_ID 
  LEFT JOIN UFCSTATS_FIGHTERS AS t3 ON t1.BLUE_FIGHTER_ID = t3.FIGHTER_ID 
WHERE 
  t2.FIGHTODDSIO_FIGHTER_SLUG IS NULL;
"""

UNKNOWN_FIGHTODDSIO_COMPLETED_BOUTS = """
SELECT 
  FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
  FIGHTER_NAME 
FROM 
  FIGHTODDSIO_BOUTS AS t1 
  LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_1_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
  LEFT JOIN FIGHTODDSIO_FIGHTERS AS t3 ON t1.FIGHTER_1_SLUG = t3.FIGHTER_SLUG 
WHERE 
  t2.UFCSTATS_FIGHTER_ID IS NULL 
UNION 
SELECT 
  FIGHTER_SLUG AS FIGHTODDSIO_FIGHTER_SLUG, 
  FIGHTER_NAME 
FROM 
  FIGHTODDSIO_BOUTS AS t1 
  LEFT JOIN FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_2_SLUG = t2.FIGHTODDSIO_FIGHTER_SLUG 
  LEFT JOIN FIGHTODDSIO_FIGHTERS AS t3 ON t1.FIGHTER_2_SLUG = t3.FIGHTER_SLUG 
WHERE 
  t2.UFCSTATS_FIGHTER_ID IS NULL;
"""
