name: Rankings Pipeline

on:
    workflow_dispatch:
    # workflow_run:
    #     workflows: ["Results Pipeline"]
    #     types:
    #         - completed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                python-version: "3.9.18"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pandas scrapy scrapy-user-agents thefuzz geopy
           
            - name: Run rankings pipeline for most recent monthly rankings
              run: python pipeline_run.py RANKINGS
        
            - name: Commit files and push changes
              run: |
                git config user.email "actions@users.noreply.github.com"
                git config user.name "Automated"
                git add -A
                timestamp=$(date -u)
                git commit -m "Latest monthly rankings: ${timestamp}" || exit 0
                git push