name: Results (All) Pipeline

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                python-version: "3.9.16"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pandas scrapy scrapy-user-agents thefuzz geopy
           
            - name: Run results pipeline for all results
              run: python pipeline_run.py results_all
        
            - name: Commit files and push changes
              run: |
                git config user.email "actions@users.noreply.github.com"
                git config user.name "Automated"
                git add -A
                timestamp=$(date -u)
                git commit -m "Latest data (reset): ${timestamp}" || exit 0
                git push
