name: Scrape all stats from UFCStats website

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * MON"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: "3.8"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pandas numpy bs4 lxml requests tqdm
            
            - name: Run scraper
              run: python scripts/scrape_all_stats.py
        
            - name: Commit files
              run: |
                git config user.email "actions@users.noreply.github.com"
                git config user.name "Automated"
                git add -A
                timestamp=$(date -u)
                git commit -m "Latest data: ${timestamp}" || exit 0
                git push