name: Upcoming Event Pipeline

on:
    workflow_dispatch:
    schedule:
        - cron: "0 12 * * WED"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                python-version: "3.9.16"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pandas scrapy scrapy-user-agents thefuzz geopy
            
            - name: Run upcoming event pipeline
              run: python pipeline_run.py upcoming_event
            
            - name: Commit files and push changes
              run: |
                git config user.email "actions@users.noreply.github.com"
                git config user.name "Automated"
                git add -A
                timestamp=$(date -u)
                git commit -m "Latest data: ${timestamp}" || exit 0
                git push